layout_spectrum: 0.6381237010625513
typography_spectrum: 0.24385510444521238
color:
  brandStrength: 0.25062462769559407
  lightness: 0.3752187543887977
  saturation: 0.44761628922738944
  rhythmicContrast: 0.5285086033006411
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
github: true
author:
  name: Erik Holtan
  email: erik.holtan@gmail.com
  url: 'https://erikpedia.science'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/29685e97-1d0d-4094-931b-8c2fa20649cc.png
name: Erikpedia
url: 'https://www.erikpedia.science'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: About
    id: 7e9698ea-344c-4e3c-94d5-b9a53cee659b
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8887931d-2695-4d2b-89ab-23606455e24c.png
title: Erikpedia
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/b49f4724-3b5e-491f-97e3-c7d956a48b90.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/b49f4724-3b5e-491f-97e3-c7d956a48b90.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'It''s not science, it''s Erikpedia'
